server:
  port: 8080

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://192.168.21.129:3306/course?autoReconnect=true&useSSL=false&characterEncoding=utf-8&zeroDateTimeBehavior=convertToNull&serverTimezone=Asia/Shanghai&rewriteBatchedStatements=true
    username: test
    password: 12345678
    initial-size: 1
    min-idle: 1
    max-active: 20
    max-wait: 10000
    time-between-eviction-runs-millis: 60000
  redis:
    host: 192.168.21.129
    port: 6379
  cache:
    type: redis

# mybatis配置
mybatis-plus:
  configuration:
    cache-enabled: true
    use-generated-keys: true
    default-executor-type: REUSE
    use-actual-param-name: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl # 测试环境，控制台打印SQL



# swagger配置
springfox:
  documentation:
    enabled: true #是否启用

# 日志配置
logging:
  config: classpath:logConfig/logback-dev.xml

# 消息队列配置
rocketmq:
  name-server: 192.168.21.129:9876
  producer:
    group: my-group
    send-message-timeout: 3000 #发送超时时间毫秒 默认3000
    retry-times-when-send-failed: 2 #同步发送失败时重试次数 默认2